# manual test, whose output needs human to evaluate if execution makes sense
# (need automated tests)

import UsageRanking

def debug_soln(soln):
    print(soln.vid_cnt)
    print(soln.vid_rank)
    print(soln.rank_vid)
    print(soln.cnt_min_rank)
    print('')

soln = UsageRanking()
soln.videoViewed('a')
soln.videoViewed('b')
soln.videoViewed('c')
debug_soln(soln)
soln.videoViewed('b')
debug_soln(soln)
soln.videoViewed('b')
debug_soln(soln)
soln.videoViewed('c')
debug_soln(soln)
soln.videoViewed('c')
debug_soln(soln)
soln.videoViewed('a')
debug_soln(soln)
soln.videoViewed('c')
debug_soln(soln)
soln.videoViewed('d')
debug_soln(soln)
soln.videoViewed('d')
debug_soln(soln)
soln.videoViewed('d')
debug_soln(soln)
soln.videoViewed('d')
debug_soln(soln)
soln.videoViewed('d')
debug_soln(soln)
print(list(soln.getTopVideos()))