# manual test, whose output needs human to evaluate if execution makes sense
# (need automated tests)

from urank.UsageRanking import UsageRanking

def debug_soln(soln):
    print(str(soln))

soln = UsageRanking()
soln.use_item('a')
soln.use_item('b')
soln.use_item('c')
debug_soln(soln)
soln.use_item('b')
debug_soln(soln)
soln.use_item('b')
debug_soln(soln)
soln.use_item('c')
debug_soln(soln)
soln.use_item('c')
debug_soln(soln)
soln.use_item('a')
debug_soln(soln)
soln.use_item('c')
debug_soln(soln)
soln.use_item('d')
debug_soln(soln)
soln.use_item('d')
debug_soln(soln)
soln.use_item('d')
debug_soln(soln)
soln.use_item('d')
debug_soln(soln)
soln.use_item('d')
debug_soln(soln)
print(list(soln.top_items(10)))